/*
 * L3vels Api
 * L3vels API for Game developers
 *
 * The version of the OpenAPI document: 0.3
 * Contact: support@l3vels.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.l3vels.sdk.models;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Asset
 */
@JsonPropertyOrder({
  Asset.JSON_PROPERTY_ID,
  Asset.JSON_PROPERTY_TOKEN_ID,
  Asset.JSON_PROPERTY_NAME,
  Asset.JSON_PROPERTY_PARENT_ID,
  Asset.JSON_PROPERTY_PROPERTIES,
  Asset.JSON_PROPERTY_ATTRIBUTES,
  Asset.JSON_PROPERTY_DESCRIPTION,
  Asset.JSON_PROPERTY_STATUS,
  Asset.JSON_PROPERTY_PRICE,
  Asset.JSON_PROPERTY_SUPPLY,
  Asset.JSON_PROPERTY_MINTED_AMOUNT,
  Asset.JSON_PROPERTY_ASSET_TYPE,
  Asset.JSON_PROPERTY_ASSET_URL,
  Asset.JSON_PROPERTY_MEDIAS,
  Asset.JSON_PROPERTY_MAIN_MEDIA,
  Asset.JSON_PROPERTY_ACCOUNT_ID,
  Asset.JSON_PROPERTY_PROJECT_ID,
  Asset.JSON_PROPERTY_COLLECTION_ID,
  Asset.JSON_PROPERTY_CREATED_ON,
  Asset.JSON_PROPERTY_MODIFIED_ON,
  Asset.JSON_PROPERTY_CREATED_BY,
  Asset.JSON_PROPERTY_MODIFIED_BY
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-04-21T12:10:08.229616-05:00[America/Bogota]")
public class Asset {
  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_TOKEN_ID = "token_id";
  private BigDecimal tokenId;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_PARENT_ID = "parent_id";
  private String parentId;

  public static final String JSON_PROPERTY_PROPERTIES = "properties";
  private Object properties;

  public static final String JSON_PROPERTY_ATTRIBUTES = "attributes";
  private Object attributes;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  private String description;

  public static final String JSON_PROPERTY_STATUS = "status";
  private String status;

  public static final String JSON_PROPERTY_PRICE = "price";
  private BigDecimal price;

  public static final String JSON_PROPERTY_SUPPLY = "supply";
  private BigDecimal supply;

  public static final String JSON_PROPERTY_MINTED_AMOUNT = "minted_amount";
  private BigDecimal mintedAmount;

  public static final String JSON_PROPERTY_ASSET_TYPE = "asset_type";
  private String assetType;

  public static final String JSON_PROPERTY_ASSET_URL = "asset_url";
  private String assetUrl;

  public static final String JSON_PROPERTY_MEDIAS = "medias";
  private List<String> medias = new ArrayList<>();

  public static final String JSON_PROPERTY_MAIN_MEDIA = "main_media";
  private String mainMedia;

  public static final String JSON_PROPERTY_ACCOUNT_ID = "account_id";
  private BigDecimal accountId;

  public static final String JSON_PROPERTY_PROJECT_ID = "project_id";
  private String projectId;

  public static final String JSON_PROPERTY_COLLECTION_ID = "collection_id";
  private String collectionId;

  public static final String JSON_PROPERTY_CREATED_ON = "created_on";
  private OffsetDateTime createdOn;

  public static final String JSON_PROPERTY_MODIFIED_ON = "modified_on";
  private OffsetDateTime modifiedOn;

  public static final String JSON_PROPERTY_CREATED_BY = "created_by";
  private BigDecimal createdBy;

  public static final String JSON_PROPERTY_MODIFIED_BY = "modified_by";
  private BigDecimal modifiedBy;

  public Asset() {
  }

  public Asset id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * The unique identifier for the asset entity.
   * @return id
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(String id) {
    this.id = id;
  }


  public Asset tokenId(BigDecimal tokenId) {
    
    this.tokenId = tokenId;
    return this;
  }

   /**
   * The token id of the asset.
   * @return tokenId
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TOKEN_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getTokenId() {
    return tokenId;
  }


  @JsonProperty(JSON_PROPERTY_TOKEN_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTokenId(BigDecimal tokenId) {
    this.tokenId = tokenId;
  }


  public Asset name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * The name of the asset.
   * @return name
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(String name) {
    this.name = name;
  }


  public Asset parentId(String parentId) {
    
    this.parentId = parentId;
    return this;
  }

   /**
   * ID of the parent asset.
   * @return parentId
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PARENT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getParentId() {
    return parentId;
  }


  @JsonProperty(JSON_PROPERTY_PARENT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setParentId(String parentId) {
    this.parentId = parentId;
  }


  public Asset properties(Object properties) {
    
    this.properties = properties;
    return this;
  }

   /**
   * Custom properties of the asset.
   * @return properties
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PROPERTIES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Object getProperties() {
    return properties;
  }


  @JsonProperty(JSON_PROPERTY_PROPERTIES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setProperties(Object properties) {
    this.properties = properties;
  }


  public Asset attributes(Object attributes) {
    
    this.attributes = attributes;
    return this;
  }

   /**
   * Custom attributes of the asset.
   * @return attributes
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ATTRIBUTES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Object getAttributes() {
    return attributes;
  }


  @JsonProperty(JSON_PROPERTY_ATTRIBUTES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAttributes(Object attributes) {
    this.attributes = attributes;
  }


  public Asset description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * The description of the asset.
   * @return description
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDescription(String description) {
    this.description = description;
  }


  public Asset status(String status) {
    
    this.status = status;
    return this;
  }

   /**
   * The status of the asset.
   * @return status
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStatus(String status) {
    this.status = status;
  }


  public Asset price(BigDecimal price) {
    
    this.price = price;
    return this;
  }

   /**
   * The price of the asset.
   * @return price
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PRICE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getPrice() {
    return price;
  }


  @JsonProperty(JSON_PROPERTY_PRICE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPrice(BigDecimal price) {
    this.price = price;
  }


  public Asset supply(BigDecimal supply) {
    
    this.supply = supply;
    return this;
  }

   /**
   * The supply of the asset.
   * @return supply
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SUPPLY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getSupply() {
    return supply;
  }


  @JsonProperty(JSON_PROPERTY_SUPPLY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSupply(BigDecimal supply) {
    this.supply = supply;
  }


  public Asset mintedAmount(BigDecimal mintedAmount) {
    
    this.mintedAmount = mintedAmount;
    return this;
  }

   /**
   * The minted amount of the asset.
   * @return mintedAmount
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MINTED_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getMintedAmount() {
    return mintedAmount;
  }


  @JsonProperty(JSON_PROPERTY_MINTED_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMintedAmount(BigDecimal mintedAmount) {
    this.mintedAmount = mintedAmount;
  }


  public Asset assetType(String assetType) {
    
    this.assetType = assetType;
    return this;
  }

   /**
   * The asset type. Can be main or nested.
   * @return assetType
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ASSET_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getAssetType() {
    return assetType;
  }


  @JsonProperty(JSON_PROPERTY_ASSET_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAssetType(String assetType) {
    this.assetType = assetType;
  }


  public Asset assetUrl(String assetUrl) {
    
    this.assetUrl = assetUrl;
    return this;
  }

   /**
   * The asset URL.
   * @return assetUrl
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ASSET_URL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getAssetUrl() {
    return assetUrl;
  }


  @JsonProperty(JSON_PROPERTY_ASSET_URL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAssetUrl(String assetUrl) {
    this.assetUrl = assetUrl;
  }


  public Asset medias(List<String> medias) {
    
    this.medias = medias;
    return this;
  }

  public Asset addMediasItem(String mediasItem) {
    if (this.medias == null) {
      this.medias = new ArrayList<>();
    }
    this.medias.add(mediasItem);
    return this;
  }

   /**
   * Additional images associated with the asset, such as screenshots or promotional images.
   * @return medias
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MEDIAS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<String> getMedias() {
    return medias;
  }


  @JsonProperty(JSON_PROPERTY_MEDIAS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMedias(List<String> medias) {
    this.medias = medias;
  }


  public Asset mainMedia(String mainMedia) {
    
    this.mainMedia = mainMedia;
    return this;
  }

   /**
   * The main or featured image associated with the asset. You can set it from the Dashboard as main image.
   * @return mainMedia
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MAIN_MEDIA)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getMainMedia() {
    return mainMedia;
  }


  @JsonProperty(JSON_PROPERTY_MAIN_MEDIA)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMainMedia(String mainMedia) {
    this.mainMedia = mainMedia;
  }


  public Asset accountId(BigDecimal accountId) {
    
    this.accountId = accountId;
    return this;
  }

   /**
   * The unique identifier of the account that the Collection belongs to.
   * @return accountId
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ACCOUNT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getAccountId() {
    return accountId;
  }


  @JsonProperty(JSON_PROPERTY_ACCOUNT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAccountId(BigDecimal accountId) {
    this.accountId = accountId;
  }


  public Asset projectId(String projectId) {
    
    this.projectId = projectId;
    return this;
  }

   /**
   * The unique identifier of the project that the asset is associated with. This allows developers to organize their assets by project and helps with tracking and reporting.
   * @return projectId
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PROJECT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getProjectId() {
    return projectId;
  }


  @JsonProperty(JSON_PROPERTY_PROJECT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setProjectId(String projectId) {
    this.projectId = projectId;
  }


  public Asset collectionId(String collectionId) {
    
    this.collectionId = collectionId;
    return this;
  }

   /**
   * The unique identifier of the collection that the asset is associated with. This allows developers to organize their collections by project and helps with tracking and reporting.
   * @return collectionId
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_COLLECTION_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCollectionId() {
    return collectionId;
  }


  @JsonProperty(JSON_PROPERTY_COLLECTION_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCollectionId(String collectionId) {
    this.collectionId = collectionId;
  }


  public Asset createdOn(OffsetDateTime createdOn) {
    
    this.createdOn = createdOn;
    return this;
  }

   /**
   * The date when the collection was created.
   * @return createdOn
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CREATED_ON)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getCreatedOn() {
    return createdOn;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_ON)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreatedOn(OffsetDateTime createdOn) {
    this.createdOn = createdOn;
  }


  public Asset modifiedOn(OffsetDateTime modifiedOn) {
    
    this.modifiedOn = modifiedOn;
    return this;
  }

   /**
   * The date when the collection was last modified.
   * @return modifiedOn
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MODIFIED_ON)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getModifiedOn() {
    return modifiedOn;
  }


  @JsonProperty(JSON_PROPERTY_MODIFIED_ON)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setModifiedOn(OffsetDateTime modifiedOn) {
    this.modifiedOn = modifiedOn;
  }


  public Asset createdBy(BigDecimal createdBy) {
    
    this.createdBy = createdBy;
    return this;
  }

   /**
   * The Id of the user who created the collection.
   * @return createdBy
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CREATED_BY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getCreatedBy() {
    return createdBy;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_BY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreatedBy(BigDecimal createdBy) {
    this.createdBy = createdBy;
  }


  public Asset modifiedBy(BigDecimal modifiedBy) {
    
    this.modifiedBy = modifiedBy;
    return this;
  }

   /**
   * The Id of the user who last modified the collection.
   * @return modifiedBy
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MODIFIED_BY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getModifiedBy() {
    return modifiedBy;
  }


  @JsonProperty(JSON_PROPERTY_MODIFIED_BY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setModifiedBy(BigDecimal modifiedBy) {
    this.modifiedBy = modifiedBy;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Asset asset = (Asset) o;
    return Objects.equals(this.id, asset.id) &&
        Objects.equals(this.tokenId, asset.tokenId) &&
        Objects.equals(this.name, asset.name) &&
        Objects.equals(this.parentId, asset.parentId) &&
        Objects.equals(this.properties, asset.properties) &&
        Objects.equals(this.attributes, asset.attributes) &&
        Objects.equals(this.description, asset.description) &&
        Objects.equals(this.status, asset.status) &&
        Objects.equals(this.price, asset.price) &&
        Objects.equals(this.supply, asset.supply) &&
        Objects.equals(this.mintedAmount, asset.mintedAmount) &&
        Objects.equals(this.assetType, asset.assetType) &&
        Objects.equals(this.assetUrl, asset.assetUrl) &&
        Objects.equals(this.medias, asset.medias) &&
        Objects.equals(this.mainMedia, asset.mainMedia) &&
        Objects.equals(this.accountId, asset.accountId) &&
        Objects.equals(this.projectId, asset.projectId) &&
        Objects.equals(this.collectionId, asset.collectionId) &&
        Objects.equals(this.createdOn, asset.createdOn) &&
        Objects.equals(this.modifiedOn, asset.modifiedOn) &&
        Objects.equals(this.createdBy, asset.createdBy) &&
        Objects.equals(this.modifiedBy, asset.modifiedBy);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, tokenId, name, parentId, properties, attributes, description, status, price, supply, mintedAmount, assetType, assetUrl, medias, mainMedia, accountId, projectId, collectionId, createdOn, modifiedOn, createdBy, modifiedBy);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Asset {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    tokenId: ").append(toIndentedString(tokenId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    parentId: ").append(toIndentedString(parentId)).append("\n");
    sb.append("    properties: ").append(toIndentedString(properties)).append("\n");
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    supply: ").append(toIndentedString(supply)).append("\n");
    sb.append("    mintedAmount: ").append(toIndentedString(mintedAmount)).append("\n");
    sb.append("    assetType: ").append(toIndentedString(assetType)).append("\n");
    sb.append("    assetUrl: ").append(toIndentedString(assetUrl)).append("\n");
    sb.append("    medias: ").append(toIndentedString(medias)).append("\n");
    sb.append("    mainMedia: ").append(toIndentedString(mainMedia)).append("\n");
    sb.append("    accountId: ").append(toIndentedString(accountId)).append("\n");
    sb.append("    projectId: ").append(toIndentedString(projectId)).append("\n");
    sb.append("    collectionId: ").append(toIndentedString(collectionId)).append("\n");
    sb.append("    createdOn: ").append(toIndentedString(createdOn)).append("\n");
    sb.append("    modifiedOn: ").append(toIndentedString(modifiedOn)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    modifiedBy: ").append(toIndentedString(modifiedBy)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

