/*
 * L3vels Api
 * L3vels API for Game developers
 *
 * The version of the OpenAPI document: 0.3
 * Contact: support@l3vels.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.l3vels.sdk.models;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Collection
 */
@JsonPropertyOrder({
  Collection.JSON_PROPERTY_ID,
  Collection.JSON_PROPERTY_UNIQUE_ID,
  Collection.JSON_PROPERTY_NAME,
  Collection.JSON_PROPERTY_DESCRIPTION,
  Collection.JSON_PROPERTY_LOGO_IMAGE,
  Collection.JSON_PROPERTY_MEDIAS,
  Collection.JSON_PROPERTY_MAIN_MEDIA,
  Collection.JSON_PROPERTY_URL,
  Collection.JSON_PROPERTY_WEB_LINK,
  Collection.JSON_PROPERTY_SUPPLY,
  Collection.JSON_PROPERTY_CUSTOM_PROPERTY_PROPS,
  Collection.JSON_PROPERTY_SOCIAL_LINKS,
  Collection.JSON_PROPERTY_CUSTOM_ASSET_PROPS,
  Collection.JSON_PROPERTY_CATEGORIES,
  Collection.JSON_PROPERTY_STATUS,
  Collection.JSON_PROPERTY_ACCOUNT_ID,
  Collection.JSON_PROPERTY_PROJECT_ID,
  Collection.JSON_PROPERTY_CREATED_ON,
  Collection.JSON_PROPERTY_MODIFIED_ON,
  Collection.JSON_PROPERTY_CREATED_BY,
  Collection.JSON_PROPERTY_MODIFIED_BY
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-04-21T12:10:08.229616-05:00[America/Bogota]")
public class Collection {
  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_UNIQUE_ID = "unique_id";
  private String uniqueId;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  private String description;

  public static final String JSON_PROPERTY_LOGO_IMAGE = "logo_image";
  private String logoImage;

  public static final String JSON_PROPERTY_MEDIAS = "medias";
  private List<String> medias = new ArrayList<>();

  public static final String JSON_PROPERTY_MAIN_MEDIA = "main_media";
  private String mainMedia;

  public static final String JSON_PROPERTY_URL = "url";
  private String url;

  public static final String JSON_PROPERTY_WEB_LINK = "web_link";
  private String webLink;

  public static final String JSON_PROPERTY_SUPPLY = "supply";
  private BigDecimal supply;

  public static final String JSON_PROPERTY_CUSTOM_PROPERTY_PROPS = "custom_property_props";
  private Object customPropertyProps;

  public static final String JSON_PROPERTY_SOCIAL_LINKS = "social_links";
  private List<String> socialLinks = new ArrayList<>();

  public static final String JSON_PROPERTY_CUSTOM_ASSET_PROPS = "custom_asset_props";
  private Object customAssetProps;

  public static final String JSON_PROPERTY_CATEGORIES = "categories";
  private Object categories;

  public static final String JSON_PROPERTY_STATUS = "status";
  private String status;

  public static final String JSON_PROPERTY_ACCOUNT_ID = "account_id";
  private BigDecimal accountId;

  public static final String JSON_PROPERTY_PROJECT_ID = "project_id";
  private String projectId;

  public static final String JSON_PROPERTY_CREATED_ON = "created_on";
  private OffsetDateTime createdOn;

  public static final String JSON_PROPERTY_MODIFIED_ON = "modified_on";
  private OffsetDateTime modifiedOn;

  public static final String JSON_PROPERTY_CREATED_BY = "created_by";
  private BigDecimal createdBy;

  public static final String JSON_PROPERTY_MODIFIED_BY = "modified_by";
  private BigDecimal modifiedBy;

  public Collection() {
  }

  public Collection id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * The unique identifier for the collection entity.
   * @return id
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(String id) {
    this.id = id;
  }


  public Collection uniqueId(String uniqueId) {
    
    this.uniqueId = uniqueId;
    return this;
  }

   /**
   * The unique identifier that can be provided by game studio.
   * @return uniqueId
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_UNIQUE_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getUniqueId() {
    return uniqueId;
  }


  @JsonProperty(JSON_PROPERTY_UNIQUE_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUniqueId(String uniqueId) {
    this.uniqueId = uniqueId;
  }


  public Collection name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * The name of the collection.
   * @return name
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(String name) {
    this.name = name;
  }


  public Collection description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * A brief description of the collection.
   * @return description
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDescription(String description) {
    this.description = description;
  }


  public Collection logoImage(String logoImage) {
    
    this.logoImage = logoImage;
    return this;
  }

   /**
   * An image representing the collection&#39;s logo.
   * @return logoImage
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_LOGO_IMAGE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getLogoImage() {
    return logoImage;
  }


  @JsonProperty(JSON_PROPERTY_LOGO_IMAGE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLogoImage(String logoImage) {
    this.logoImage = logoImage;
  }


  public Collection medias(List<String> medias) {
    
    this.medias = medias;
    return this;
  }

  public Collection addMediasItem(String mediasItem) {
    if (this.medias == null) {
      this.medias = new ArrayList<>();
    }
    this.medias.add(mediasItem);
    return this;
  }

   /**
   * Additional images associated with the collection, such as screenshots or promotional images.
   * @return medias
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MEDIAS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<String> getMedias() {
    return medias;
  }


  @JsonProperty(JSON_PROPERTY_MEDIAS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMedias(List<String> medias) {
    this.medias = medias;
  }


  public Collection mainMedia(String mainMedia) {
    
    this.mainMedia = mainMedia;
    return this;
  }

   /**
   * The main or featured image associated with the game. You can set it from the dashboard as main image.
   * @return mainMedia
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MAIN_MEDIA)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getMainMedia() {
    return mainMedia;
  }


  @JsonProperty(JSON_PROPERTY_MAIN_MEDIA)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMainMedia(String mainMedia) {
    this.mainMedia = mainMedia;
  }


  public Collection url(String url) {
    
    this.url = url;
    return this;
  }

   /**
   * A unique URL for the collection on the L3vels platform.
   * @return url
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_URL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getUrl() {
    return url;
  }


  @JsonProperty(JSON_PROPERTY_URL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUrl(String url) {
    this.url = url;
  }


  public Collection webLink(String webLink) {
    
    this.webLink = webLink;
    return this;
  }

   /**
   * A URL link to the collection&#39;s webpage.
   * @return webLink
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_WEB_LINK)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getWebLink() {
    return webLink;
  }


  @JsonProperty(JSON_PROPERTY_WEB_LINK)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setWebLink(String webLink) {
    this.webLink = webLink;
  }


  public Collection supply(BigDecimal supply) {
    
    this.supply = supply;
    return this;
  }

   /**
   * The supply represents the number of assets that are available within the Collection.
   * @return supply
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SUPPLY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getSupply() {
    return supply;
  }


  @JsonProperty(JSON_PROPERTY_SUPPLY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSupply(BigDecimal supply) {
    this.supply = supply;
  }


  public Collection customPropertyProps(Object customPropertyProps) {
    
    this.customPropertyProps = customPropertyProps;
    return this;
  }

   /**
   * Custom properties that are unique to the collection and defined by the developer to categorize and filter them.
   * @return customPropertyProps
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CUSTOM_PROPERTY_PROPS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Object getCustomPropertyProps() {
    return customPropertyProps;
  }


  @JsonProperty(JSON_PROPERTY_CUSTOM_PROPERTY_PROPS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCustomPropertyProps(Object customPropertyProps) {
    this.customPropertyProps = customPropertyProps;
  }


  public Collection socialLinks(List<String> socialLinks) {
    
    this.socialLinks = socialLinks;
    return this;
  }

  public Collection addSocialLinksItem(String socialLinksItem) {
    if (this.socialLinks == null) {
      this.socialLinks = new ArrayList<>();
    }
    this.socialLinks.add(socialLinksItem);
    return this;
  }

   /**
   * Additional social links associated with the collection
   * @return socialLinks
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SOCIAL_LINKS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<String> getSocialLinks() {
    return socialLinks;
  }


  @JsonProperty(JSON_PROPERTY_SOCIAL_LINKS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSocialLinks(List<String> socialLinks) {
    this.socialLinks = socialLinks;
  }


  public Collection customAssetProps(Object customAssetProps) {
    
    this.customAssetProps = customAssetProps;
    return this;
  }

   /**
   * Custom assets fields associated with the collection.
   * @return customAssetProps
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CUSTOM_ASSET_PROPS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Object getCustomAssetProps() {
    return customAssetProps;
  }


  @JsonProperty(JSON_PROPERTY_CUSTOM_ASSET_PROPS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCustomAssetProps(Object customAssetProps) {
    this.customAssetProps = customAssetProps;
  }


  public Collection categories(Object categories) {
    
    this.categories = categories;
    return this;
  }

   /**
   * The category or categories that the collection belongs to.
   * @return categories
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CATEGORIES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Object getCategories() {
    return categories;
  }


  @JsonProperty(JSON_PROPERTY_CATEGORIES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCategories(Object categories) {
    this.categories = categories;
  }


  public Collection status(String status) {
    
    this.status = status;
    return this;
  }

   /**
   * The current status of the collection. Possible values are: Draft, Active
   * @return status
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStatus(String status) {
    this.status = status;
  }


  public Collection accountId(BigDecimal accountId) {
    
    this.accountId = accountId;
    return this;
  }

   /**
   * The unique identifier of the account that the Collection belongs to.
   * @return accountId
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ACCOUNT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getAccountId() {
    return accountId;
  }


  @JsonProperty(JSON_PROPERTY_ACCOUNT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAccountId(BigDecimal accountId) {
    this.accountId = accountId;
  }


  public Collection projectId(String projectId) {
    
    this.projectId = projectId;
    return this;
  }

   /**
   * The unique identifier of the project that the collection is associated with. This allows developers to organize their collections by project and helps with tracking and reporting.
   * @return projectId
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PROJECT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getProjectId() {
    return projectId;
  }


  @JsonProperty(JSON_PROPERTY_PROJECT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setProjectId(String projectId) {
    this.projectId = projectId;
  }


  public Collection createdOn(OffsetDateTime createdOn) {
    
    this.createdOn = createdOn;
    return this;
  }

   /**
   * The date when the collection was created.
   * @return createdOn
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CREATED_ON)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getCreatedOn() {
    return createdOn;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_ON)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreatedOn(OffsetDateTime createdOn) {
    this.createdOn = createdOn;
  }


  public Collection modifiedOn(OffsetDateTime modifiedOn) {
    
    this.modifiedOn = modifiedOn;
    return this;
  }

   /**
   * The date when the collection was last modified.
   * @return modifiedOn
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MODIFIED_ON)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getModifiedOn() {
    return modifiedOn;
  }


  @JsonProperty(JSON_PROPERTY_MODIFIED_ON)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setModifiedOn(OffsetDateTime modifiedOn) {
    this.modifiedOn = modifiedOn;
  }


  public Collection createdBy(BigDecimal createdBy) {
    
    this.createdBy = createdBy;
    return this;
  }

   /**
   * The Id of the user who created the collection.
   * @return createdBy
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CREATED_BY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getCreatedBy() {
    return createdBy;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_BY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreatedBy(BigDecimal createdBy) {
    this.createdBy = createdBy;
  }


  public Collection modifiedBy(BigDecimal modifiedBy) {
    
    this.modifiedBy = modifiedBy;
    return this;
  }

   /**
   * The Id of the user who last modified the collection.
   * @return modifiedBy
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MODIFIED_BY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getModifiedBy() {
    return modifiedBy;
  }


  @JsonProperty(JSON_PROPERTY_MODIFIED_BY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setModifiedBy(BigDecimal modifiedBy) {
    this.modifiedBy = modifiedBy;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Collection collection = (Collection) o;
    return Objects.equals(this.id, collection.id) &&
        Objects.equals(this.uniqueId, collection.uniqueId) &&
        Objects.equals(this.name, collection.name) &&
        Objects.equals(this.description, collection.description) &&
        Objects.equals(this.logoImage, collection.logoImage) &&
        Objects.equals(this.medias, collection.medias) &&
        Objects.equals(this.mainMedia, collection.mainMedia) &&
        Objects.equals(this.url, collection.url) &&
        Objects.equals(this.webLink, collection.webLink) &&
        Objects.equals(this.supply, collection.supply) &&
        Objects.equals(this.customPropertyProps, collection.customPropertyProps) &&
        Objects.equals(this.socialLinks, collection.socialLinks) &&
        Objects.equals(this.customAssetProps, collection.customAssetProps) &&
        Objects.equals(this.categories, collection.categories) &&
        Objects.equals(this.status, collection.status) &&
        Objects.equals(this.accountId, collection.accountId) &&
        Objects.equals(this.projectId, collection.projectId) &&
        Objects.equals(this.createdOn, collection.createdOn) &&
        Objects.equals(this.modifiedOn, collection.modifiedOn) &&
        Objects.equals(this.createdBy, collection.createdBy) &&
        Objects.equals(this.modifiedBy, collection.modifiedBy);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, uniqueId, name, description, logoImage, medias, mainMedia, url, webLink, supply, customPropertyProps, socialLinks, customAssetProps, categories, status, accountId, projectId, createdOn, modifiedOn, createdBy, modifiedBy);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Collection {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    uniqueId: ").append(toIndentedString(uniqueId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    logoImage: ").append(toIndentedString(logoImage)).append("\n");
    sb.append("    medias: ").append(toIndentedString(medias)).append("\n");
    sb.append("    mainMedia: ").append(toIndentedString(mainMedia)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    webLink: ").append(toIndentedString(webLink)).append("\n");
    sb.append("    supply: ").append(toIndentedString(supply)).append("\n");
    sb.append("    customPropertyProps: ").append(toIndentedString(customPropertyProps)).append("\n");
    sb.append("    socialLinks: ").append(toIndentedString(socialLinks)).append("\n");
    sb.append("    customAssetProps: ").append(toIndentedString(customAssetProps)).append("\n");
    sb.append("    categories: ").append(toIndentedString(categories)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    accountId: ").append(toIndentedString(accountId)).append("\n");
    sb.append("    projectId: ").append(toIndentedString(projectId)).append("\n");
    sb.append("    createdOn: ").append(toIndentedString(createdOn)).append("\n");
    sb.append("    modifiedOn: ").append(toIndentedString(modifiedOn)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    modifiedBy: ").append(toIndentedString(modifiedBy)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

