/*
 * L3vels Api
 * L3vels API for Game developers
 *
 * The version of the OpenAPI document: 0.3
 * Contact: support@l3vels.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.l3vels.sdk.models;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * MintBatchDto
 */
@JsonPropertyOrder({
  MintBatchDto.JSON_PROPERTY_PROJECT_ID,
  MintBatchDto.JSON_PROPERTY_COLLECTION_ID,
  MintBatchDto.JSON_PROPERTY_PLAYER_ADDRESS,
  MintBatchDto.JSON_PROPERTY_PLAYER_ID,
  MintBatchDto.JSON_PROPERTY_ASSETS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-04-21T12:10:08.229616-05:00[America/Bogota]")
public class MintBatchDto {
  public static final String JSON_PROPERTY_PROJECT_ID = "project_id";
  private String projectId;

  public static final String JSON_PROPERTY_COLLECTION_ID = "collection_id";
  private String collectionId;

  public static final String JSON_PROPERTY_PLAYER_ADDRESS = "player_address";
  private String playerAddress;

  public static final String JSON_PROPERTY_PLAYER_ID = "player_id";
  private String playerId;

  public static final String JSON_PROPERTY_ASSETS = "assets";
  private List<String> assets = new ArrayList<>();

  public MintBatchDto() {
  }

  public MintBatchDto projectId(String projectId) {
    
    this.projectId = projectId;
    return this;
  }

   /**
   * Project Id
   * @return projectId
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PROJECT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getProjectId() {
    return projectId;
  }


  @JsonProperty(JSON_PROPERTY_PROJECT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setProjectId(String projectId) {
    this.projectId = projectId;
  }


  public MintBatchDto collectionId(String collectionId) {
    
    this.collectionId = collectionId;
    return this;
  }

   /**
   * Collection Id
   * @return collectionId
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_COLLECTION_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCollectionId() {
    return collectionId;
  }


  @JsonProperty(JSON_PROPERTY_COLLECTION_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCollectionId(String collectionId) {
    this.collectionId = collectionId;
  }


  public MintBatchDto playerAddress(String playerAddress) {
    
    this.playerAddress = playerAddress;
    return this;
  }

   /**
   * Player address to mint token to
   * @return playerAddress
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PLAYER_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getPlayerAddress() {
    return playerAddress;
  }


  @JsonProperty(JSON_PROPERTY_PLAYER_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPlayerAddress(String playerAddress) {
    this.playerAddress = playerAddress;
  }


  public MintBatchDto playerId(String playerId) {
    
    this.playerId = playerId;
    return this;
  }

   /**
   * Player ID to mint to. You can provide this or player_address
   * @return playerId
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PLAYER_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getPlayerId() {
    return playerId;
  }


  @JsonProperty(JSON_PROPERTY_PLAYER_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPlayerId(String playerId) {
    this.playerId = playerId;
  }


  public MintBatchDto assets(List<String> assets) {
    
    this.assets = assets;
    return this;
  }

  public MintBatchDto addAssetsItem(String assetsItem) {
    if (this.assets == null) {
      this.assets = new ArrayList<>();
    }
    this.assets.add(assetsItem);
    return this;
  }

   /**
   * Array of tokens to mint
   * @return assets
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ASSETS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<String> getAssets() {
    return assets;
  }


  @JsonProperty(JSON_PROPERTY_ASSETS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAssets(List<String> assets) {
    this.assets = assets;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MintBatchDto mintBatchDto = (MintBatchDto) o;
    return Objects.equals(this.projectId, mintBatchDto.projectId) &&
        Objects.equals(this.collectionId, mintBatchDto.collectionId) &&
        Objects.equals(this.playerAddress, mintBatchDto.playerAddress) &&
        Objects.equals(this.playerId, mintBatchDto.playerId) &&
        Objects.equals(this.assets, mintBatchDto.assets);
  }

  @Override
  public int hashCode() {
    return Objects.hash(projectId, collectionId, playerAddress, playerId, assets);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MintBatchDto {\n");
    sb.append("    projectId: ").append(toIndentedString(projectId)).append("\n");
    sb.append("    collectionId: ").append(toIndentedString(collectionId)).append("\n");
    sb.append("    playerAddress: ").append(toIndentedString(playerAddress)).append("\n");
    sb.append("    playerId: ").append(toIndentedString(playerId)).append("\n");
    sb.append("    assets: ").append(toIndentedString(assets)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

