/*
 * L3vels Api
 * L3vels API for Game developers
 *
 * The version of the OpenAPI document: 0.3
 * Contact: support@l3vels.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.l3vels.sdk.models;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.l3vels.sdk.models.MintDtoAsset;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * MintDto
 */
@JsonPropertyOrder({
  MintDto.JSON_PROPERTY_CONTRACT_ID,
  MintDto.JSON_PROPERTY_PROJECT_ID,
  MintDto.JSON_PROPERTY_COLLECTION_ID,
  MintDto.JSON_PROPERTY_PLAYER_ADDRESS,
  MintDto.JSON_PROPERTY_PLAYER_ID,
  MintDto.JSON_PROPERTY_ASSET
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-04-21T12:10:08.229616-05:00[America/Bogota]")
public class MintDto {
  public static final String JSON_PROPERTY_CONTRACT_ID = "contract_id";
  private String contractId;

  public static final String JSON_PROPERTY_PROJECT_ID = "project_id";
  private String projectId;

  public static final String JSON_PROPERTY_COLLECTION_ID = "collection_id";
  private String collectionId;

  public static final String JSON_PROPERTY_PLAYER_ADDRESS = "player_address";
  private String playerAddress;

  public static final String JSON_PROPERTY_PLAYER_ID = "player_id";
  private String playerId;

  public static final String JSON_PROPERTY_ASSET = "asset";
  private MintDtoAsset asset;

  public MintDto() {
  }

  public MintDto contractId(String contractId) {
    
    this.contractId = contractId;
    return this;
  }

   /**
   * Contract ID
   * @return contractId
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONTRACT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getContractId() {
    return contractId;
  }


  @JsonProperty(JSON_PROPERTY_CONTRACT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContractId(String contractId) {
    this.contractId = contractId;
  }


  public MintDto projectId(String projectId) {
    
    this.projectId = projectId;
    return this;
  }

   /**
   * Game/project ID. Example: Call of Duty
   * @return projectId
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PROJECT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getProjectId() {
    return projectId;
  }


  @JsonProperty(JSON_PROPERTY_PROJECT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setProjectId(String projectId) {
    this.projectId = projectId;
  }


  public MintDto collectionId(String collectionId) {
    
    this.collectionId = collectionId;
    return this;
  }

   /**
   * Collection ID to use. Example: Characters, Weapons, etc.
   * @return collectionId
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_COLLECTION_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCollectionId() {
    return collectionId;
  }


  @JsonProperty(JSON_PROPERTY_COLLECTION_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCollectionId(String collectionId) {
    this.collectionId = collectionId;
  }


  public MintDto playerAddress(String playerAddress) {
    
    this.playerAddress = playerAddress;
    return this;
  }

   /**
   * Player address to mint token to. You can provide player ID or player address
   * @return playerAddress
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PLAYER_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPlayerAddress() {
    return playerAddress;
  }


  @JsonProperty(JSON_PROPERTY_PLAYER_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPlayerAddress(String playerAddress) {
    this.playerAddress = playerAddress;
  }


  public MintDto playerId(String playerId) {
    
    this.playerId = playerId;
    return this;
  }

   /**
   * Player ID to mint to. You can provide player ID or player address
   * @return playerId
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PLAYER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPlayerId() {
    return playerId;
  }


  @JsonProperty(JSON_PROPERTY_PLAYER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPlayerId(String playerId) {
    this.playerId = playerId;
  }


  public MintDto asset(MintDtoAsset asset) {
    
    this.asset = asset;
    return this;
  }

   /**
   * Get asset
   * @return asset
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ASSET)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public MintDtoAsset getAsset() {
    return asset;
  }


  @JsonProperty(JSON_PROPERTY_ASSET)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAsset(MintDtoAsset asset) {
    this.asset = asset;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MintDto mintDto = (MintDto) o;
    return Objects.equals(this.contractId, mintDto.contractId) &&
        Objects.equals(this.projectId, mintDto.projectId) &&
        Objects.equals(this.collectionId, mintDto.collectionId) &&
        Objects.equals(this.playerAddress, mintDto.playerAddress) &&
        Objects.equals(this.playerId, mintDto.playerId) &&
        Objects.equals(this.asset, mintDto.asset);
  }

  @Override
  public int hashCode() {
    return Objects.hash(contractId, projectId, collectionId, playerAddress, playerId, asset);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MintDto {\n");
    sb.append("    contractId: ").append(toIndentedString(contractId)).append("\n");
    sb.append("    projectId: ").append(toIndentedString(projectId)).append("\n");
    sb.append("    collectionId: ").append(toIndentedString(collectionId)).append("\n");
    sb.append("    playerAddress: ").append(toIndentedString(playerAddress)).append("\n");
    sb.append("    playerId: ").append(toIndentedString(playerId)).append("\n");
    sb.append("    asset: ").append(toIndentedString(asset)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

