/*
 * L3vels Api
 * L3vels API for Game developers
 *
 * The version of the OpenAPI document: 0.3
 * Contact: support@l3vels.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.l3vels.sdk.models;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * PlayerAsset
 */
@JsonPropertyOrder({
  PlayerAsset.JSON_PROPERTY_ID,
  PlayerAsset.JSON_PROPERTY_AMOUNT,
  PlayerAsset.JSON_PROPERTY_PLAYER_ID,
  PlayerAsset.JSON_PROPERTY_ASSET_ID,
  PlayerAsset.JSON_PROPERTY_COLLECTION_ID,
  PlayerAsset.JSON_PROPERTY_ACCOUNT_ID,
  PlayerAsset.JSON_PROPERTY_PROJECT_ID,
  PlayerAsset.JSON_PROPERTY_CREATED_ON,
  PlayerAsset.JSON_PROPERTY_MODIFIED_ON,
  PlayerAsset.JSON_PROPERTY_CREATED_BY,
  PlayerAsset.JSON_PROPERTY_MODIFIED_BY
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-04-21T12:10:08.229616-05:00[America/Bogota]")
public class PlayerAsset {
  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_AMOUNT = "amount";
  private BigDecimal amount;

  public static final String JSON_PROPERTY_PLAYER_ID = "player_id";
  private String playerId;

  public static final String JSON_PROPERTY_ASSET_ID = "asset_id";
  private String assetId;

  public static final String JSON_PROPERTY_COLLECTION_ID = "collection_id";
  private String collectionId;

  public static final String JSON_PROPERTY_ACCOUNT_ID = "account_id";
  private BigDecimal accountId;

  public static final String JSON_PROPERTY_PROJECT_ID = "project_id";
  private String projectId;

  public static final String JSON_PROPERTY_CREATED_ON = "created_on";
  private OffsetDateTime createdOn;

  public static final String JSON_PROPERTY_MODIFIED_ON = "modified_on";
  private OffsetDateTime modifiedOn;

  public static final String JSON_PROPERTY_CREATED_BY = "created_by";
  private BigDecimal createdBy;

  public static final String JSON_PROPERTY_MODIFIED_BY = "modified_by";
  private BigDecimal modifiedBy;

  public PlayerAsset() {
  }

  public PlayerAsset id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * The unique identifier for the Player asset entity.
   * @return id
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(String id) {
    this.id = id;
  }


  public PlayerAsset amount(BigDecimal amount) {
    
    this.amount = amount;
    return this;
  }

   /**
   * The amount of the specific asset that the player has.
   * @return amount
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getAmount() {
    return amount;
  }


  @JsonProperty(JSON_PROPERTY_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAmount(BigDecimal amount) {
    this.amount = amount;
  }


  public PlayerAsset playerId(String playerId) {
    
    this.playerId = playerId;
    return this;
  }

   /**
   * The unique identifier of the player that the asset is associated with.
   * @return playerId
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PLAYER_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getPlayerId() {
    return playerId;
  }


  @JsonProperty(JSON_PROPERTY_PLAYER_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPlayerId(String playerId) {
    this.playerId = playerId;
  }


  public PlayerAsset assetId(String assetId) {
    
    this.assetId = assetId;
    return this;
  }

   /**
   * The unique identifier of the asset that the asset is associated with.
   * @return assetId
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ASSET_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getAssetId() {
    return assetId;
  }


  @JsonProperty(JSON_PROPERTY_ASSET_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAssetId(String assetId) {
    this.assetId = assetId;
  }


  public PlayerAsset collectionId(String collectionId) {
    
    this.collectionId = collectionId;
    return this;
  }

   /**
   * The unique identifier of the collection that the Player asset is associated with.
   * @return collectionId
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_COLLECTION_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCollectionId() {
    return collectionId;
  }


  @JsonProperty(JSON_PROPERTY_COLLECTION_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCollectionId(String collectionId) {
    this.collectionId = collectionId;
  }


  public PlayerAsset accountId(BigDecimal accountId) {
    
    this.accountId = accountId;
    return this;
  }

   /**
   * The unique identifier of the account that the Player belongs to.
   * @return accountId
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ACCOUNT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getAccountId() {
    return accountId;
  }


  @JsonProperty(JSON_PROPERTY_ACCOUNT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAccountId(BigDecimal accountId) {
    this.accountId = accountId;
  }


  public PlayerAsset projectId(String projectId) {
    
    this.projectId = projectId;
    return this;
  }

   /**
   * The unique identifier of the project that the Player is associated with. This allows developers to organize their players by project and helps with tracking and reporting.
   * @return projectId
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PROJECT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getProjectId() {
    return projectId;
  }


  @JsonProperty(JSON_PROPERTY_PROJECT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setProjectId(String projectId) {
    this.projectId = projectId;
  }


  public PlayerAsset createdOn(OffsetDateTime createdOn) {
    
    this.createdOn = createdOn;
    return this;
  }

   /**
   * The date when the player was created.
   * @return createdOn
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CREATED_ON)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getCreatedOn() {
    return createdOn;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_ON)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreatedOn(OffsetDateTime createdOn) {
    this.createdOn = createdOn;
  }


  public PlayerAsset modifiedOn(OffsetDateTime modifiedOn) {
    
    this.modifiedOn = modifiedOn;
    return this;
  }

   /**
   * The date when the player was last modified.
   * @return modifiedOn
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MODIFIED_ON)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getModifiedOn() {
    return modifiedOn;
  }


  @JsonProperty(JSON_PROPERTY_MODIFIED_ON)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setModifiedOn(OffsetDateTime modifiedOn) {
    this.modifiedOn = modifiedOn;
  }


  public PlayerAsset createdBy(BigDecimal createdBy) {
    
    this.createdBy = createdBy;
    return this;
  }

   /**
   * The Id of the user who created the player.
   * @return createdBy
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CREATED_BY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getCreatedBy() {
    return createdBy;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_BY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreatedBy(BigDecimal createdBy) {
    this.createdBy = createdBy;
  }


  public PlayerAsset modifiedBy(BigDecimal modifiedBy) {
    
    this.modifiedBy = modifiedBy;
    return this;
  }

   /**
   * The Id of the user who last modified the player.
   * @return modifiedBy
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MODIFIED_BY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getModifiedBy() {
    return modifiedBy;
  }


  @JsonProperty(JSON_PROPERTY_MODIFIED_BY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setModifiedBy(BigDecimal modifiedBy) {
    this.modifiedBy = modifiedBy;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PlayerAsset playerAsset = (PlayerAsset) o;
    return Objects.equals(this.id, playerAsset.id) &&
        Objects.equals(this.amount, playerAsset.amount) &&
        Objects.equals(this.playerId, playerAsset.playerId) &&
        Objects.equals(this.assetId, playerAsset.assetId) &&
        Objects.equals(this.collectionId, playerAsset.collectionId) &&
        Objects.equals(this.accountId, playerAsset.accountId) &&
        Objects.equals(this.projectId, playerAsset.projectId) &&
        Objects.equals(this.createdOn, playerAsset.createdOn) &&
        Objects.equals(this.modifiedOn, playerAsset.modifiedOn) &&
        Objects.equals(this.createdBy, playerAsset.createdBy) &&
        Objects.equals(this.modifiedBy, playerAsset.modifiedBy);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, amount, playerId, assetId, collectionId, accountId, projectId, createdOn, modifiedOn, createdBy, modifiedBy);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PlayerAsset {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    playerId: ").append(toIndentedString(playerId)).append("\n");
    sb.append("    assetId: ").append(toIndentedString(assetId)).append("\n");
    sb.append("    collectionId: ").append(toIndentedString(collectionId)).append("\n");
    sb.append("    accountId: ").append(toIndentedString(accountId)).append("\n");
    sb.append("    projectId: ").append(toIndentedString(projectId)).append("\n");
    sb.append("    createdOn: ").append(toIndentedString(createdOn)).append("\n");
    sb.append("    modifiedOn: ").append(toIndentedString(modifiedOn)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    modifiedBy: ").append(toIndentedString(modifiedBy)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

