/*
 * L3vels Api
 * L3vels API for Game developers
 *
 * The version of the OpenAPI document: 0.3
 * Contact: support@l3vels.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.l3vels.sdk.models;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Player
 */
@JsonPropertyOrder({
  Player.JSON_PROPERTY_ID,
  Player.JSON_PROPERTY_UNIQUE_ID,
  Player.JSON_PROPERTY_NAME,
  Player.JSON_PROPERTY_USERNAME,
  Player.JSON_PROPERTY_EMAIL,
  Player.JSON_PROPERTY_AVATAR,
  Player.JSON_PROPERTY_CUSTOM_PROPS,
  Player.JSON_PROPERTY_LAST_SEEN,
  Player.JSON_PROPERTY_ACCOUNT_ID,
  Player.JSON_PROPERTY_PROJECT_ID,
  Player.JSON_PROPERTY_CREATED_ON,
  Player.JSON_PROPERTY_MODIFIED_ON,
  Player.JSON_PROPERTY_CREATED_BY,
  Player.JSON_PROPERTY_MODIFIED_BY,
  Player.JSON_PROPERTY_IS_CREATE_WALLET
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-04-21T12:10:08.229616-05:00[America/Bogota]")
public class Player {
  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_UNIQUE_ID = "unique_id";
  private String uniqueId;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_USERNAME = "username";
  private String username;

  public static final String JSON_PROPERTY_EMAIL = "email";
  private String email;

  public static final String JSON_PROPERTY_AVATAR = "avatar";
  private String avatar;

  public static final String JSON_PROPERTY_CUSTOM_PROPS = "custom_props";
  private Object customProps;

  public static final String JSON_PROPERTY_LAST_SEEN = "last_seen";
  private OffsetDateTime lastSeen;

  public static final String JSON_PROPERTY_ACCOUNT_ID = "account_id";
  private BigDecimal accountId;

  public static final String JSON_PROPERTY_PROJECT_ID = "project_id";
  private String projectId;

  public static final String JSON_PROPERTY_CREATED_ON = "created_on";
  private OffsetDateTime createdOn;

  public static final String JSON_PROPERTY_MODIFIED_ON = "modified_on";
  private OffsetDateTime modifiedOn;

  public static final String JSON_PROPERTY_CREATED_BY = "created_by";
  private BigDecimal createdBy;

  public static final String JSON_PROPERTY_MODIFIED_BY = "modified_by";
  private BigDecimal modifiedBy;

  public static final String JSON_PROPERTY_IS_CREATE_WALLET = "is_create_wallet";
  private Boolean isCreateWallet;

  public Player() {
  }

  public Player id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * The unique identifier for the Player entity.
   * @return id
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(String id) {
    this.id = id;
  }


  public Player uniqueId(String uniqueId) {
    
    this.uniqueId = uniqueId;
    return this;
  }

   /**
   * The unique ID of the Player that can be provided by customers or generated by us.
   * @return uniqueId
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_UNIQUE_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getUniqueId() {
    return uniqueId;
  }


  @JsonProperty(JSON_PROPERTY_UNIQUE_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUniqueId(String uniqueId) {
    this.uniqueId = uniqueId;
  }


  public Player name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * The name of the player
   * @return name
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(String name) {
    this.name = name;
  }


  public Player username(String username) {
    
    this.username = username;
    return this;
  }

   /**
   * Username of the player
   * @return username
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_USERNAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getUsername() {
    return username;
  }


  @JsonProperty(JSON_PROPERTY_USERNAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUsername(String username) {
    this.username = username;
  }


  public Player email(String email) {
    
    this.email = email;
    return this;
  }

   /**
   * Email of the player
   * @return email
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_EMAIL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getEmail() {
    return email;
  }


  @JsonProperty(JSON_PROPERTY_EMAIL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEmail(String email) {
    this.email = email;
  }


  public Player avatar(String avatar) {
    
    this.avatar = avatar;
    return this;
  }

   /**
   * Avatar URL of the player
   * @return avatar
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_AVATAR)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getAvatar() {
    return avatar;
  }


  @JsonProperty(JSON_PROPERTY_AVATAR)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAvatar(String avatar) {
    this.avatar = avatar;
  }


  public Player customProps(Object customProps) {
    
    this.customProps = customProps;
    return this;
  }

   /**
   * Custom props for player
   * @return customProps
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CUSTOM_PROPS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Object getCustomProps() {
    return customProps;
  }


  @JsonProperty(JSON_PROPERTY_CUSTOM_PROPS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCustomProps(Object customProps) {
    this.customProps = customProps;
  }


  public Player lastSeen(OffsetDateTime lastSeen) {
    
    this.lastSeen = lastSeen;
    return this;
  }

   /**
   * The date when player was active last time
   * @return lastSeen
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_LAST_SEEN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getLastSeen() {
    return lastSeen;
  }


  @JsonProperty(JSON_PROPERTY_LAST_SEEN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLastSeen(OffsetDateTime lastSeen) {
    this.lastSeen = lastSeen;
  }


  public Player accountId(BigDecimal accountId) {
    
    this.accountId = accountId;
    return this;
  }

   /**
   * The unique identifier of the account that the Player belongs to.
   * @return accountId
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ACCOUNT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getAccountId() {
    return accountId;
  }


  @JsonProperty(JSON_PROPERTY_ACCOUNT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAccountId(BigDecimal accountId) {
    this.accountId = accountId;
  }


  public Player projectId(String projectId) {
    
    this.projectId = projectId;
    return this;
  }

   /**
   * The unique identifier of the project that the Player is associated with. This allows developers to organize their players by project and helps with tracking and reporting. Example: Player Jack is associated with project Fortnite.
   * @return projectId
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PROJECT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getProjectId() {
    return projectId;
  }


  @JsonProperty(JSON_PROPERTY_PROJECT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setProjectId(String projectId) {
    this.projectId = projectId;
  }


  public Player createdOn(OffsetDateTime createdOn) {
    
    this.createdOn = createdOn;
    return this;
  }

   /**
   * The date when the player was created.
   * @return createdOn
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CREATED_ON)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getCreatedOn() {
    return createdOn;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_ON)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreatedOn(OffsetDateTime createdOn) {
    this.createdOn = createdOn;
  }


  public Player modifiedOn(OffsetDateTime modifiedOn) {
    
    this.modifiedOn = modifiedOn;
    return this;
  }

   /**
   * The date when the player was last modified.
   * @return modifiedOn
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MODIFIED_ON)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getModifiedOn() {
    return modifiedOn;
  }


  @JsonProperty(JSON_PROPERTY_MODIFIED_ON)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setModifiedOn(OffsetDateTime modifiedOn) {
    this.modifiedOn = modifiedOn;
  }


  public Player createdBy(BigDecimal createdBy) {
    
    this.createdBy = createdBy;
    return this;
  }

   /**
   * The Id of the user who created the player.
   * @return createdBy
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CREATED_BY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getCreatedBy() {
    return createdBy;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_BY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreatedBy(BigDecimal createdBy) {
    this.createdBy = createdBy;
  }


  public Player modifiedBy(BigDecimal modifiedBy) {
    
    this.modifiedBy = modifiedBy;
    return this;
  }

   /**
   * The Id of the user who last modified the player.
   * @return modifiedBy
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MODIFIED_BY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getModifiedBy() {
    return modifiedBy;
  }


  @JsonProperty(JSON_PROPERTY_MODIFIED_BY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setModifiedBy(BigDecimal modifiedBy) {
    this.modifiedBy = modifiedBy;
  }


  public Player isCreateWallet(Boolean isCreateWallet) {
    
    this.isCreateWallet = isCreateWallet;
    return this;
  }

   /**
   * Boolean value indicating whether the player has wallet or not
   * @return isCreateWallet
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_IS_CREATE_WALLET)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getIsCreateWallet() {
    return isCreateWallet;
  }


  @JsonProperty(JSON_PROPERTY_IS_CREATE_WALLET)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIsCreateWallet(Boolean isCreateWallet) {
    this.isCreateWallet = isCreateWallet;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Player player = (Player) o;
    return Objects.equals(this.id, player.id) &&
        Objects.equals(this.uniqueId, player.uniqueId) &&
        Objects.equals(this.name, player.name) &&
        Objects.equals(this.username, player.username) &&
        Objects.equals(this.email, player.email) &&
        Objects.equals(this.avatar, player.avatar) &&
        Objects.equals(this.customProps, player.customProps) &&
        Objects.equals(this.lastSeen, player.lastSeen) &&
        Objects.equals(this.accountId, player.accountId) &&
        Objects.equals(this.projectId, player.projectId) &&
        Objects.equals(this.createdOn, player.createdOn) &&
        Objects.equals(this.modifiedOn, player.modifiedOn) &&
        Objects.equals(this.createdBy, player.createdBy) &&
        Objects.equals(this.modifiedBy, player.modifiedBy) &&
        Objects.equals(this.isCreateWallet, player.isCreateWallet);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, uniqueId, name, username, email, avatar, customProps, lastSeen, accountId, projectId, createdOn, modifiedOn, createdBy, modifiedBy, isCreateWallet);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Player {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    uniqueId: ").append(toIndentedString(uniqueId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    avatar: ").append(toIndentedString(avatar)).append("\n");
    sb.append("    customProps: ").append(toIndentedString(customProps)).append("\n");
    sb.append("    lastSeen: ").append(toIndentedString(lastSeen)).append("\n");
    sb.append("    accountId: ").append(toIndentedString(accountId)).append("\n");
    sb.append("    projectId: ").append(toIndentedString(projectId)).append("\n");
    sb.append("    createdOn: ").append(toIndentedString(createdOn)).append("\n");
    sb.append("    modifiedOn: ").append(toIndentedString(modifiedOn)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    modifiedBy: ").append(toIndentedString(modifiedBy)).append("\n");
    sb.append("    isCreateWallet: ").append(toIndentedString(isCreateWallet)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

