/*
 * L3vels Api
 * L3vels API for Game developers
 *
 * The version of the OpenAPI document: 0.3
 * Contact: support@l3vels.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.l3vels.sdk.models;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * SetContractUriDto
 */
@JsonPropertyOrder({
  SetContractUriDto.JSON_PROPERTY_PROJECT_ID,
  SetContractUriDto.JSON_PROPERTY_COLLECTION_ID,
  SetContractUriDto.JSON_PROPERTY_CONTRACT_URI
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-04-21T12:10:08.229616-05:00[America/Bogota]")
public class SetContractUriDto {
  public static final String JSON_PROPERTY_PROJECT_ID = "project_id";
  private String projectId;

  public static final String JSON_PROPERTY_COLLECTION_ID = "collection_id";
  private String collectionId;

  public static final String JSON_PROPERTY_CONTRACT_URI = "contract_uri";
  private String contractUri;

  public SetContractUriDto() {
  }

  public SetContractUriDto projectId(String projectId) {
    
    this.projectId = projectId;
    return this;
  }

   /**
   * Project Id
   * @return projectId
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PROJECT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getProjectId() {
    return projectId;
  }


  @JsonProperty(JSON_PROPERTY_PROJECT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setProjectId(String projectId) {
    this.projectId = projectId;
  }


  public SetContractUriDto collectionId(String collectionId) {
    
    this.collectionId = collectionId;
    return this;
  }

   /**
   * Collection Id
   * @return collectionId
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_COLLECTION_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCollectionId() {
    return collectionId;
  }


  @JsonProperty(JSON_PROPERTY_COLLECTION_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCollectionId(String collectionId) {
    this.collectionId = collectionId;
  }


  public SetContractUriDto contractUri(String contractUri) {
    
    this.contractUri = contractUri;
    return this;
  }

   /**
   * Contract URI
   * @return contractUri
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CONTRACT_URI)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getContractUri() {
    return contractUri;
  }


  @JsonProperty(JSON_PROPERTY_CONTRACT_URI)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setContractUri(String contractUri) {
    this.contractUri = contractUri;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SetContractUriDto setContractUriDto = (SetContractUriDto) o;
    return Objects.equals(this.projectId, setContractUriDto.projectId) &&
        Objects.equals(this.collectionId, setContractUriDto.collectionId) &&
        Objects.equals(this.contractUri, setContractUriDto.contractUri);
  }

  @Override
  public int hashCode() {
    return Objects.hash(projectId, collectionId, contractUri);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SetContractUriDto {\n");
    sb.append("    projectId: ").append(toIndentedString(projectId)).append("\n");
    sb.append("    collectionId: ").append(toIndentedString(collectionId)).append("\n");
    sb.append("    contractUri: ").append(toIndentedString(contractUri)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

