/*
 * L3vels Api
 * L3vels API for Game developers
 *
 * The version of the OpenAPI document: 0.3
 * Contact: support@l3vels.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.l3vels.sdk.models;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * UpdateAssetDto
 */
@JsonPropertyOrder({
  UpdateAssetDto.JSON_PROPERTY_NAME,
  UpdateAssetDto.JSON_PROPERTY_DESCRIPTION,
  UpdateAssetDto.JSON_PROPERTY_PRICE,
  UpdateAssetDto.JSON_PROPERTY_SUPPLY,
  UpdateAssetDto.JSON_PROPERTY_ASSET_URL,
  UpdateAssetDto.JSON_PROPERTY_CUSTOM_PROPS,
  UpdateAssetDto.JSON_PROPERTY_COLLECTION_ID,
  UpdateAssetDto.JSON_PROPERTY_PROJECT_ID
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-04-21T12:10:08.229616-05:00[America/Bogota]")
public class UpdateAssetDto {
  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  private String description;

  public static final String JSON_PROPERTY_PRICE = "price";
  private BigDecimal price;

  public static final String JSON_PROPERTY_SUPPLY = "supply";
  private BigDecimal supply;

  public static final String JSON_PROPERTY_ASSET_URL = "asset_url";
  private String assetUrl;

  public static final String JSON_PROPERTY_CUSTOM_PROPS = "custom_props";
  private Object customProps;

  public static final String JSON_PROPERTY_COLLECTION_ID = "collection_id";
  private String collectionId;

  public static final String JSON_PROPERTY_PROJECT_ID = "project_id";
  private String projectId;

  public UpdateAssetDto() {
  }

  public UpdateAssetDto name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * The name of the asset.
   * @return name
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(String name) {
    this.name = name;
  }


  public UpdateAssetDto description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * The story of asset.
   * @return description
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(String description) {
    this.description = description;
  }


  public UpdateAssetDto price(BigDecimal price) {
    
    this.price = price;
    return this;
  }

   /**
   * Price of asset
   * @return price
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PRICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getPrice() {
    return price;
  }


  @JsonProperty(JSON_PROPERTY_PRICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPrice(BigDecimal price) {
    this.price = price;
  }


  public UpdateAssetDto supply(BigDecimal supply) {
    
    this.supply = supply;
    return this;
  }

   /**
   * Supply of asset
   * @return supply
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SUPPLY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getSupply() {
    return supply;
  }


  @JsonProperty(JSON_PROPERTY_SUPPLY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSupply(BigDecimal supply) {
    this.supply = supply;
  }


  public UpdateAssetDto assetUrl(String assetUrl) {
    
    this.assetUrl = assetUrl;
    return this;
  }

   /**
   * Asset URL
   * @return assetUrl
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ASSET_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAssetUrl() {
    return assetUrl;
  }


  @JsonProperty(JSON_PROPERTY_ASSET_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAssetUrl(String assetUrl) {
    this.assetUrl = assetUrl;
  }


  public UpdateAssetDto customProps(Object customProps) {
    
    this.customProps = customProps;
    return this;
  }

   /**
   * Custom props for asset.
   * @return customProps
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CUSTOM_PROPS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getCustomProps() {
    return customProps;
  }


  @JsonProperty(JSON_PROPERTY_CUSTOM_PROPS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCustomProps(Object customProps) {
    this.customProps = customProps;
  }


  public UpdateAssetDto collectionId(String collectionId) {
    
    this.collectionId = collectionId;
    return this;
  }

   /**
   * Collection ID to find and update the asset in. Example: Update AK-47 asset in Weapons collection.
   * @return collectionId
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_COLLECTION_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCollectionId() {
    return collectionId;
  }


  @JsonProperty(JSON_PROPERTY_COLLECTION_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCollectionId(String collectionId) {
    this.collectionId = collectionId;
  }


  public UpdateAssetDto projectId(String projectId) {
    
    this.projectId = projectId;
    return this;
  }

   /**
   * Game/project ID to update the asset in. Example: Call of Duty
   * @return projectId
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PROJECT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getProjectId() {
    return projectId;
  }


  @JsonProperty(JSON_PROPERTY_PROJECT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setProjectId(String projectId) {
    this.projectId = projectId;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateAssetDto updateAssetDto = (UpdateAssetDto) o;
    return Objects.equals(this.name, updateAssetDto.name) &&
        Objects.equals(this.description, updateAssetDto.description) &&
        Objects.equals(this.price, updateAssetDto.price) &&
        Objects.equals(this.supply, updateAssetDto.supply) &&
        Objects.equals(this.assetUrl, updateAssetDto.assetUrl) &&
        Objects.equals(this.customProps, updateAssetDto.customProps) &&
        Objects.equals(this.collectionId, updateAssetDto.collectionId) &&
        Objects.equals(this.projectId, updateAssetDto.projectId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, description, price, supply, assetUrl, customProps, collectionId, projectId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateAssetDto {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    supply: ").append(toIndentedString(supply)).append("\n");
    sb.append("    assetUrl: ").append(toIndentedString(assetUrl)).append("\n");
    sb.append("    customProps: ").append(toIndentedString(customProps)).append("\n");
    sb.append("    collectionId: ").append(toIndentedString(collectionId)).append("\n");
    sb.append("    projectId: ").append(toIndentedString(projectId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

