/*
 * L3vels Api
 * L3vels API for Game developers
 *
 * The version of the OpenAPI document: 0.3
 * Contact: support@l3vels.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.l3vels.sdk.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Collection
 */
public class CollectionTest {
    private final Collection model = new Collection();

    /**
     * Model tests for Collection
     */
    @Test
    public void testCollection() {
        // TODO: test Collection
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'uniqueId'
     */
    @Test
    public void uniqueIdTest() {
        // TODO: test uniqueId
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'logoImage'
     */
    @Test
    public void logoImageTest() {
        // TODO: test logoImage
    }

    /**
     * Test the property 'medias'
     */
    @Test
    public void mediasTest() {
        // TODO: test medias
    }

    /**
     * Test the property 'mainMedia'
     */
    @Test
    public void mainMediaTest() {
        // TODO: test mainMedia
    }

    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }

    /**
     * Test the property 'webLink'
     */
    @Test
    public void webLinkTest() {
        // TODO: test webLink
    }

    /**
     * Test the property 'supply'
     */
    @Test
    public void supplyTest() {
        // TODO: test supply
    }

    /**
     * Test the property 'customPropertyProps'
     */
    @Test
    public void customPropertyPropsTest() {
        // TODO: test customPropertyProps
    }

    /**
     * Test the property 'socialLinks'
     */
    @Test
    public void socialLinksTest() {
        // TODO: test socialLinks
    }

    /**
     * Test the property 'customAssetProps'
     */
    @Test
    public void customAssetPropsTest() {
        // TODO: test customAssetProps
    }

    /**
     * Test the property 'categories'
     */
    @Test
    public void categoriesTest() {
        // TODO: test categories
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'accountId'
     */
    @Test
    public void accountIdTest() {
        // TODO: test accountId
    }

    /**
     * Test the property 'projectId'
     */
    @Test
    public void projectIdTest() {
        // TODO: test projectId
    }

    /**
     * Test the property 'createdOn'
     */
    @Test
    public void createdOnTest() {
        // TODO: test createdOn
    }

    /**
     * Test the property 'modifiedOn'
     */
    @Test
    public void modifiedOnTest() {
        // TODO: test modifiedOn
    }

    /**
     * Test the property 'createdBy'
     */
    @Test
    public void createdByTest() {
        // TODO: test createdBy
    }

    /**
     * Test the property 'modifiedBy'
     */
    @Test
    public void modifiedByTest() {
        // TODO: test modifiedBy
    }

}
