/*
 * L3vels Api
 * L3vels API for Game developers
 *
 * The version of the OpenAPI document: 0.3
 * Contact: support@l3vels.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.l3vels.sdk.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.l3vels.sdk.models.MintDtoAsset;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for MintDto
 */
public class MintDtoTest {
    private final MintDto model = new MintDto();

    /**
     * Model tests for MintDto
     */
    @Test
    public void testMintDto() {
        // TODO: test MintDto
    }

    /**
     * Test the property 'contractId'
     */
    @Test
    public void contractIdTest() {
        // TODO: test contractId
    }

    /**
     * Test the property 'projectId'
     */
    @Test
    public void projectIdTest() {
        // TODO: test projectId
    }

    /**
     * Test the property 'collectionId'
     */
    @Test
    public void collectionIdTest() {
        // TODO: test collectionId
    }

    /**
     * Test the property 'playerAddress'
     */
    @Test
    public void playerAddressTest() {
        // TODO: test playerAddress
    }

    /**
     * Test the property 'playerId'
     */
    @Test
    public void playerIdTest() {
        // TODO: test playerId
    }

    /**
     * Test the property 'asset'
     */
    @Test
    public void assetTest() {
        // TODO: test asset
    }

}
