/*
 * L3vels Api
 * L3vels API for Game developers
 *
 * The version of the OpenAPI document: 0.3
 * Contact: support@l3vels.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.l3vels.sdk.api;

import com.l3vels.sdk.models.SetContractUriDto;
import com.l3vels.sdk.models.SetSaleStatusDto;
import org.junit.Test;
import org.junit.Ignore;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ContractApi
 */
@Ignore
public class ContractApiTest {

    private final ContractApi api = new ContractApi();

    
    /**
     * Collection size
     *
     * Get size of collection
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void contractControllerCollectionSizeTest() {
        String authorization = null;
        String collectionId = null;
        String projectId = null;
        api.contractControllerCollectionSize(authorization, collectionId, projectId);

        // TODO: test validations
    }
    
    /**
     * Get Contract URI
     *
     * Gets contract uri of contract
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void contractControllerContractUriTest() {
        String authorization = null;
        String collectionId = null;
        String projectId = null;
        api.contractControllerContractUri(authorization, collectionId, projectId);

        // TODO: test validations
    }
    
    /**
     * Update Contract URI
     *
     * Update Contract URI
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void contractControllerSetContractUriTest() {
        String authorization = null;
        SetContractUriDto setContractUriDto = null;
        api.contractControllerSetContractUri(authorization, setContractUriDto);

        // TODO: test validations
    }
    
    /**
     * Update Sale status
     *
     * Update Sale status to PAUSED, PRE_SALE or PUBLIC
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void contractControllerSetSaleStatusTest() {
        String authorization = null;
        SetSaleStatusDto setSaleStatusDto = null;
        api.contractControllerSetSaleStatus(authorization, setSaleStatusDto);

        // TODO: test validations
    }
    
}
