/*
 * L3vels Api
 * L3vels API for Game developers
 *
 * The version of the OpenAPI document: 0.3
 * Contact: support@l3vels.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.l3vels.sdk.api;

import com.l3vels.sdk.models.Project;
import org.junit.Test;
import org.junit.Ignore;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for GameApi
 */
@Ignore
public class GameApiTest {

    private final GameApi api = new GameApi();

    
    /**
     * Retrieve Game
     *
     * Get game/project by ID created on the platform.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void projectControllerProjectByIdTest() {
        String authorization = null;
        String id = null;
        Project response = api.projectControllerProjectById(authorization, id);

        // TODO: test validations
    }
    
}
