/*
 * L3vels Api
 * L3vels API for Game developers
 *
 * The version of the OpenAPI document: 0.3
 * Contact: support@l3vels.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.l3vels.sdk.api;

import java.math.BigDecimal;
import com.l3vels.sdk.models.Transaction;
import org.junit.Test;
import org.junit.Ignore;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TransactionApi
 */
@Ignore
public class TransactionApiTest {

    private final TransactionApi api = new TransactionApi();

    
    /**
     * Retrieve Transaction by ID
     *
     * Retrieve transaction by ID
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void transactionControllerTransactionByIdTest() {
        String authorization = null;
        String id = null;
        String projectId = null;
        Transaction response = api.transactionControllerTransactionById(authorization, id, projectId);

        // TODO: test validations
    }
    
    /**
     * Retrieve transactions
     *
     * Retrieve all transactions.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void transactionControllerTransactionsTest() {
        String authorization = null;
        String projectId = null;
        String collectionId = null;
        String playerId = null;
        String sort = null;
        String order = null;
        String searchText = null;
        BigDecimal limit = null;
        BigDecimal page = null;
        Transaction response = api.transactionControllerTransactions(authorization, projectId, collectionId, playerId, sort, order, searchText, limit, page);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void transactionControllerWebhookTest() {
        String authorization = null;
        api.transactionControllerWebhook(authorization);

        // TODO: test validations
    }
    
}
